-- =====================================================================
-- 05_verify.sql — generated 2026-07-05 from ERPDB
-- Run inside the client database LAST. Everything should say OK.
-- =====================================================================
SELECT 'Tables' AS ObjectType, 143 AS Expected, COUNT(*) AS Actual,
       CASE WHEN COUNT(*) >= 143 THEN 'OK' ELSE 'MISSING' END AS Status
FROM sys.tables WHERE schema_id = SCHEMA_ID('proj')
UNION ALL
SELECT 'Stored procedures', 549, COUNT(*), CASE WHEN COUNT(*) >= 549 THEN 'OK' ELSE 'MISSING' END FROM sys.procedures WHERE schema_id = SCHEMA_ID('proj')
UNION ALL
SELECT 'Functions', 3, COUNT(*), CASE WHEN COUNT(*) >= 3 THEN 'OK' ELSE 'MISSING' END FROM sys.objects WHERE schema_id = SCHEMA_ID('proj') AND type IN ('FN','TF','IF')
UNION ALL
SELECT 'Views', 15, COUNT(*), CASE WHEN COUNT(*) >= 15 THEN 'OK' ELSE 'MISSING' END FROM sys.views WHERE schema_id = SCHEMA_ID('proj')
UNION ALL
SELECT 'Triggers', 5, COUNT(*), CASE WHEN COUNT(*) >= 5 THEN 'OK' ELSE 'MISSING' END FROM sys.triggers t JOIN sys.tables tb ON t.parent_id = tb.object_id WHERE tb.schema_id = SCHEMA_ID('proj')
UNION ALL
SELECT 'Sequences', 2, COUNT(*), CASE WHEN COUNT(*) >= 2 THEN 'OK' ELSE 'MISSING' END FROM sys.sequences WHERE schema_id = SCHEMA_ID('proj');

-- Seed data:
SELECT 'TBL_ROLES' AS SeedTable, 10 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 10 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ROLES]
UNION ALL
SELECT 'TBL_MENU' AS SeedTable, 119 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 119 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_MENU]
UNION ALL
SELECT 'TBL_MENU_ACTIONS' AS SeedTable, 202 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 202 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_MENU_ACTIONS]
UNION ALL
SELECT 'TBL_ROLE_MENU' AS SeedTable, 584 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 584 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ROLE_MENU]
UNION ALL
SELECT 'TBL_ROLE_MENU_ACTION' AS SeedTable, 879 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 879 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ROLE_MENU_ACTION]
UNION ALL
SELECT 'TBL_ROLE_SECRET' AS SeedTable, 11 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 11 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ROLE_SECRET]
UNION ALL
SELECT 'TBL_VLIST' AS SeedTable, 116 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 116 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_VLIST]
UNION ALL
SELECT 'TBL_FIELD_CONFIG' AS SeedTable, 141 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 141 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_FIELD_CONFIG]
UNION ALL
SELECT 'TBL_APP_SETTINGS' AS SeedTable, 15 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 15 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_APP_SETTINGS]
UNION ALL
SELECT 'TBL_APPROVAL_MODULE' AS SeedTable, 14 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 14 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_APPROVAL_MODULE]
UNION ALL
SELECT 'TBL_DOCUMENT_TYPES' AS SeedTable, 38 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 38 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_DOCUMENT_TYPES]
UNION ALL
SELECT 'TBL_DOCUMENT_STATUS' AS SeedTable, 170 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 170 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_DOCUMENT_STATUS]
UNION ALL
SELECT 'TBL_DOCUMENT_SERIES' AS SeedTable, 20 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 20 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_DOCUMENT_SERIES]
UNION ALL
SELECT 'TBL_USER_GROUP' AS SeedTable, 6 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 6 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_USER_GROUP]
UNION ALL
SELECT 'TBL_EMAIL_TEMPLATE' AS SeedTable, 10 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 10 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_EMAIL_TEMPLATE]
UNION ALL
SELECT 'TBL_EMAIL_ALERT_CONFIG' AS SeedTable, 10 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 10 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_EMAIL_ALERT_CONFIG]
UNION ALL
SELECT 'TBL_COUNTRY' AS SeedTable, 231 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 231 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_COUNTRY]
UNION ALL
SELECT 'TBL_CURRENCY' AS SeedTable, 9 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 9 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_CURRENCY]
UNION ALL
SELECT 'TBL_CUSTOMER_CATEGORY' AS SeedTable, 2 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 2 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_CUSTOMER_CATEGORY]
UNION ALL
SELECT 'TBL_SUPPLIER_CATEGORY' AS SeedTable, 4 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 4 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_SUPPLIER_CATEGORY]
UNION ALL
SELECT 'TBL_DELIVERY_TERMS' AS SeedTable, 12 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 12 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_DELIVERY_TERMS]
UNION ALL
SELECT 'TBL_PAYMENT_TERMS' AS SeedTable, 47 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 47 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_PAYMENT_TERMS]
UNION ALL
SELECT 'TBL_PO_TERMS' AS SeedTable, 6 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 6 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_PO_TERMS]
UNION ALL
SELECT 'TBL_ISSUE_TYPE' AS SeedTable, 2 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 2 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ISSUE_TYPE]
UNION ALL
SELECT 'TBL_ITEM_TYPE' AS SeedTable, 9 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 9 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ITEM_TYPE]
UNION ALL
SELECT 'TBL_ITEM_CATEGORY' AS SeedTable, 172 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 172 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ITEM_CATEGORY]
UNION ALL
SELECT 'TBL_ITEM_UOM' AS SeedTable, 30 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 30 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_ITEM_UOM]
UNION ALL
SELECT 'TBL_JOB_STATUS' AS SeedTable, 5 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 5 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOB_STATUS]
UNION ALL
SELECT 'TBL_JOB_STAGE' AS SeedTable, 5 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 5 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOB_STAGE]
UNION ALL
SELECT 'TBL_JOBTYPE' AS SeedTable, 8 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 8 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOBTYPE]
UNION ALL
SELECT 'TBL_JOB_CATEGORY' AS SeedTable, 3 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 3 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOB_CATEGORY]
UNION ALL
SELECT 'TBL_JOB_ROLE' AS SeedTable, 5 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 5 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOB_ROLE]
UNION ALL
SELECT 'TBL_JOB_BAY' AS SeedTable, 3 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 3 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOB_BAY]
UNION ALL
SELECT 'TBL_JOB_EXPENSE_CATEGORY' AS SeedTable, 31 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 31 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_JOB_EXPENSE_CATEGORY]
UNION ALL
SELECT 'TBL_MANHOUR_RATE' AS SeedTable, 1 AS Expected, COUNT(*) AS Actual, CASE WHEN COUNT(*) >= 1 THEN 'OK' ELSE 'MISSING' END AS Status FROM [proj].[TBL_MANHOUR_RATE]
ORDER BY 1;

-- Admin login must exist:
SELECT UserName, IsActive, IsLocked FROM proj.TBL_USERS WHERE UserName = 'admin';